name: TestNG CI Workflow

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch


jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu as the runner OS (can be changed to macOS or Windows)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 11) with distribution specified
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'         # Specify Java version (11 in your case)
          distribution: 'temurin'    # Use Temurin JDK distribution (AdoptOpenJDK)
      
      # Step 3: Change directory to where the pom.xml file is located
      - name: Change directory to pom.xml location
        run: cd OrangeHRM/orangehrm-test  # Navigate to the folder containing pom.xml

      # Step 4: Run Maven to clean, install dependencies, and run TestNG tests
      - name: Build and Run Tests with Maven
        run: |
          mvn clean install           # Install dependencies
          mvn test                    # Run the tests using TestNG (Ensure testng.xml is configured)

      # Step 5: Upload test results as artifacts (Optional, if you want to upload test reports)
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: OrangeHRM/orangehrm-test/target/surefire-reports/  # Path to your test reports

