name: TestNG CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose macOS or Windows if needed

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 11) with distribution specified
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'           # Specify Java version
          distribution: 'temurin'      # Specify JDK distribution (temurin from Adoptium)

      # Step 3: Change directory to where the pom.xml file is located
      - name: Change directory to pom.xml location
        run: cd OrangeHRM/orangehrm-test  # Navigate to the folder containing pom.xml

      # Step 4: Run Maven to build and test
      - name: Build and Run Tests with Maven
        run: |
          mvn clean install           # Install dependencies
          mvn test                    # Run tests using TestNG (Ensure testng.xml is configured)

      # Step 5: Upload test results as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/  # Path to test results (ensure this matches your setup)
