name: CI Workflow for TestNG

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11 (using Zulu distribution)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Using Zulu for JDK distribution

    # Step 3: Install dependencies using Maven
    - name: Install dependencies
      run: mvn install
      working-directory: ./OrangeHRM  # Corrected directory path

    # Step 4: Run tests with Maven (TestNG tests)
    - name: Run Tests
      run: mvn test
      working-directory: ./OrangeHRM  # Corrected directory path
